### ISSUE TITLE
hard-coded "editingteacher" and "student" shortnames

### ISSUE THREAD

**Issue by danmarsden** [developerck/moodle-block_analyticswidget#6]
Sites may change the default shortnames, and doing things based on "roles" is usually incorrect.
Your plugin should implement 2 new capabilites.
one assigned to editing teachers by default, and one assigned to students by default - then your code should check if the user has this capability rather than checking for roles.

more information on this is available here:
https://moodledev.io/docs/apis/subsystems/access

Note - hard coded use of role shortnames is a blocker for approval.

**Comment by developerck** [comment]
As i wanted to show on basis of course enrolment role, and targetted for those users, so planned  a settings which will allow siteadmin to choose the roles rather than defining it with hardcoded string.
![Selection_504](https://user-images.githubusercontent.com/1241815/182439295-c30727ca-65a9-4ada-a7aa-b920290dc162.png)
This will help users to select , if there is any change.

**Comment by danmarsden** [comment]
FYI - although that gets you past the blocker for approval it is still not best practice - it would have been better to do what I suggested above - define 2 new capabilities in your plugin and assign them to teacher/student roles by default - then check those.
